// ui/src/lib/components/molecules/TaskCard.svelte
<script lang="ts">
	import { Card } from '$lib/components';
	import TaskStatusBadge from '../atoms/TaskStatusBadge.svelte';
	import { ClockIcon, UserIcon } from '$lib/components/icons';
	import type { EnhancedTask } from '$lib/types';

	interface Props {
		task: EnhancedTask;
		onclick?: () => void;
		class?: string;
	}

	let { task, onclick, class: className = '' }: Props = $props();

	// Format duration helper
	function formatDuration(seconds?: number): string {
		if (!seconds) return 'N/A';
		
		if (seconds < 60) {
			return `${Math.round(seconds)}s`;
		} else if (seconds < 3600) {
			return `${Math.round(seconds / 60)}m`;
		} else {
			return `${Math.round(seconds / 3600)}h`;
		}
	}

	// Format timestamp helper
	function formatTimestamp(timestamp?: string): string {
		if (!timestamp) return 'Never';
		
		const date = new Date(timestamp);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffHours = diffMs / (1000 * 60 * 60);
		
		if (diffHours < 1) {
			const diffMinutes = Math.round(diffMs / (1000 * 60));
			return `${diffMinutes}m ago`;
		} else if (diffHours < 24) {
			return `${Math.round(diffHours)}h ago`;
		} else {
			const diffDays = Math.round(diffHours / 24);
			return `${diffDays}d ago`;
		}
	}

	// Format triggered by helper
	function formatTriggeredBy(triggeredBy?: string): string {
		if (!triggeredBy) return 'Unknown';
		
		// Parse source_type:source_id format
		const parts = triggeredBy.split(':');
		if (parts.length === 2) {
			const [type, id] = parts;
			switch (type) {
				case 'user':
					return `User: ${id}`;
				case 'schedule':
					return 'Scheduled';
				case 'api':
					return 'API';
				case 'webhook':
					return 'Webhook';
				default:
					return triggeredBy;
			}
		}
		
		return triggeredBy;
	}

	// Determine status for badge
	const lastExecutionStatus = task.statistics.last_execution?.status || 'never_executed';
	
	// Calculate success rate percentage
	const successRatePercent = Math.round(task.statistics.success_rate);
</script>

<Card 
	variant="elevated" 
	padding="md"
	class="cursor-pointer hover:shadow-lg transition-all duration-200 {className}"
	{onclick}
	role="button"
	tabindex={0}
	onkeydown={(e) => {
		if ((e.key === 'Enter' || e.key === ' ') && onclick) {
			e.preventDefault();
			onclick();
		}
	}}
	aria-label="View task details for {task.name || task.id}"
>
	{#snippet children()}
		<div class="space-y-4">
			<!-- Header with title and status -->
			<div class="flex items-start justify-between gap-3">
				<div class="flex-1 min-w-0">
					<h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 truncate">
						{task.name || task.id}
					</h3>
					{#if task.description}
						<p class="text-sm text-gray-600 dark:text-gray-400 mt-1 line-clamp-2">
							{task.description}
						</p>
					{/if}
				</div>
				<div class="flex-shrink-0">
					<TaskStatusBadge status={lastExecutionStatus} size="sm" />
				</div>
			</div>

			<!-- Statistics row -->
			<div class="grid grid-cols-2 sm:grid-cols-3 gap-4 text-sm">
				<!-- Total executions -->
				<div class="flex flex-col">
					<span class="text-gray-500 dark:text-gray-400 text-xs uppercase tracking-wide">
						Executions
					</span>
					<span class="font-medium text-gray-900 dark:text-gray-100">
						{task.statistics.total_executions}
					</span>
				</div>

				<!-- Success rate -->
				<div class="flex flex-col">
					<span class="text-gray-500 dark:text-gray-400 text-xs uppercase tracking-wide">
						Success Rate
					</span>
					<span class="font-medium text-gray-900 dark:text-gray-100">
						{task.statistics.total_executions > 0 ? `${successRatePercent}%` : 'N/A'}
					</span>
				</div>

				<!-- Average duration -->
				<div class="flex flex-col col-span-2 sm:col-span-1">
					<span class="text-gray-500 dark:text-gray-400 text-xs uppercase tracking-wide">
						Avg Duration
					</span>
					<span class="font-medium text-gray-900 dark:text-gray-100">
						{formatDuration(task.statistics.average_duration)}
					</span>
				</div>
			</div>

			<!-- Last execution info -->
			{#if task.statistics.last_execution}
				<div class="pt-3 border-t border-gray-200 dark:border-gray-700">
					<div class="flex items-center justify-between text-sm">
						<div class="flex items-center gap-2 text-gray-600 dark:text-gray-400">
							<ClockIcon class="w-4 h-4" />
							<span>Last run: {formatTimestamp(task.statistics.last_execution.timestamp)}</span>
						</div>
						<div class="flex items-center gap-2 text-gray-600 dark:text-gray-400">
							<UserIcon class="w-4 h-4" />
							<span class="truncate max-w-24">
								{formatTriggeredBy(task.statistics.last_execution.triggered_by)}
							</span>
						</div>
					</div>
				</div>
			{:else}
				<div class="pt-3 border-t border-gray-200 dark:border-gray-700">
					<div class="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
						<ClockIcon class="w-4 h-4" />
						<span>Never executed</span>
					</div>
				</div>
			{/if}
		</div>
	{/snippet}
</Card>

// ui/src/components/tasks/TaskCard.tsx
import React from 'react';
import { Card, CardContent, CardHeader } from '../ui/Card';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { cn, formatDuration } from '../../utils';
import type { Task } from '../../types';

export interface TaskCardProps {
  task: Task;
  onExecute?: (taskId: string) => void;
  onViewDetails?: (taskId: string) => void;
  loading?: boolean;
  className?: string;
}

export const TaskCard: React.FC<TaskCardProps> = ({
  task,
  onExecute,
  onViewDetails,
  loading = false,
  className,
}) => {
  const { statistics } = task;
  const successRate = statistics.total_executions > 0 
    ? Math.round((statistics.success_count / statistics.total_executions) * 100)
    : 0;

  const getSuccessRateVariant = (rate: number) => {
    if (rate >= 90) return 'success';
    if (rate >= 70) return 'warning';
    return 'error';
  };

  // Use task name if available, otherwise fall back to ID
  const displayName = task.name || task.id;

  return (
    <Card className={cn('hover:shadow-md transition-shadow', className)}>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex-1 min-w-0">
            <h3 className="text-lg font-semibold text-gray-900 truncate">
              {displayName}
            </h3>
            {task.name && task.id !== task.name && (
              <p className="mt-1 text-xs text-gray-500 font-mono">
                ID: {task.id}
              </p>
            )}
            {task.description && (
              <p className="mt-1 text-sm text-gray-600 line-clamp-2">
                {task.description}
              </p>
            )}
          </div>
          <div className="flex items-center space-x-2 ml-4">
            <Badge variant={getSuccessRateVariant(successRate)} size="sm">
              {successRate}% success
            </Badge>
          </div>
        </div>
      </CardHeader>

      <CardContent>
        <div className="space-y-4">
          {/* Statistics Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-gray-900">
                {statistics.total_executions}
              </div>
              <div className="text-xs text-gray-500">Total Runs</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-green-600">
                {statistics.success_count}
              </div>
              <div className="text-xs text-gray-500">Successful</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-red-600">
                {statistics.failure_count}
              </div>
              <div className="text-xs text-gray-500">Failed</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">
                {formatDuration(statistics.average_duration)}
              </div>
              <div className="text-xs text-gray-500">Avg Duration</div>
            </div>
          </div>

          {/* Last Execution Info */}
          {statistics.last_execution && (
            <div className="pt-2 border-t border-gray-100">
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Last run:</span>
                <div className="flex items-center space-x-2">
                  <Badge 
                    variant={statistics.last_execution.status === 'success' ? 'success' : 'error'} 
                    size="sm"
                  >
                    {statistics.last_execution.status}
                  </Badge>
                  <span className="text-gray-600">
                    {formatDuration(statistics.last_execution.duration)}
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex items-center justify-between pt-4 border-t border-gray-200">
            <Button
              variant="outline"
              size="sm"
              onClick={() => onViewDetails?.(task.id)}
              disabled={loading}
            >
              View Details
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={() => onExecute?.(task.id)}
              loading={loading}
              disabled={loading}
            >
              Execute Task
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
