// ui/src/lib/components/atoms/Alert.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';
	import { CheckCircleIcon, ExclamationCircleIcon, XIcon } from '../icons';

	interface AlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'class'> {
		variant?: 'info' | 'success' | 'warning' | 'error';
		dismissible?: boolean;
		onclose?: () => void;
		children: Snippet;
		icon?: Snippet;
		class?: string;
	}

	let {
		variant = 'info',
		dismissible = false,
		onclose,
		children,
		icon,
		class: className = '',
		...restProps
	}: AlertProps = $props();

	// Base alert classes
	const baseClasses = [
		'flex',
		'items-start',
		'p-4',
		'rounded-lg',
		'border',
		'gap-3'
	];

	// Variant classes
	const variantClasses = {
		info: [
			'bg-blue-50',
			'border-blue-200',
			'text-blue-800',
			'dark:bg-blue-900/20',
			'dark:border-blue-800',
			'dark:text-blue-300'
		],
		success: [
			'bg-green-50',
			'border-green-200',
			'text-green-800',
			'dark:bg-green-900/20',
			'dark:border-green-800',
			'dark:text-green-300'
		],
		warning: [
			'bg-yellow-50',
			'border-yellow-200',
			'text-yellow-800',
			'dark:bg-yellow-900/20',
			'dark:border-yellow-800',
			'dark:text-yellow-300'
		],
		error: [
			'bg-red-50',
			'border-red-200',
			'text-red-800',
			'dark:bg-red-900/20',
			'dark:border-red-800',
			'dark:text-red-300'
		]
	};

	// Icon color classes for default icons
	const iconColorClasses = {
		info: 'text-blue-500 dark:text-blue-400',
		success: 'text-green-500 dark:text-green-400',
		warning: 'text-yellow-500 dark:text-yellow-400',
		error: 'text-red-500 dark:text-red-400'
	};

	// Combine all classes
	const alertClasses = [
		...baseClasses,
		...variantClasses[variant],
		className
	].join(' ');



	// Handle close action
	function handleClose() {
		onclose?.();
	}

	// Handle keyboard events for close button
	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			handleClose();
		}
	}
</script>

<div
	class={alertClasses}
	role="alert"
	aria-live="polite"
	{...restProps}
>
	<!-- Icon -->
	<div class="flex-shrink-0">
		{#if icon}
			{@render icon()}
		{:else}
			{#if variant === 'info'}
				<ExclamationCircleIcon class="w-5 h-5 {iconColorClasses[variant]}" />
			{:else if variant === 'success'}
				<CheckCircleIcon class="w-5 h-5 {iconColorClasses[variant]}" />
			{:else if variant === 'warning'}
				<ExclamationCircleIcon class="w-5 h-5 {iconColorClasses[variant]}" />
			{:else if variant === 'error'}
				<ExclamationCircleIcon class="w-5 h-5 {iconColorClasses[variant]}" />
			{/if}
		{/if}
	</div>

	<!-- Content -->
	<div class="flex-1 min-w-0">
		{@render children()}
	</div>

	<!-- Close button -->
	{#if dismissible}
		<div class="flex-shrink-0">
			<button
				type="button"
				class="inline-flex rounded-md p-1.5 hover:bg-black/5 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-transparent focus:ring-current transition-colors dark:hover:bg-white/5"
				onclick={handleClose}
				onkeydown={handleKeydown}
				aria-label="Close alert"
			>
				<XIcon class="w-4 h-4" />
			</button>
		</div>
	{/if}
</div>

// ui/src/components/ui/Alert.tsx
import React from 'react';
import { cn } from '../../utils';

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'info' | 'success' | 'warning' | 'error';
  title?: string;
  children: React.ReactNode;
  dismissible?: boolean;
  onDismiss?: () => void;
}

const alertVariants = {
  info: {
    container: 'bg-blue-50 border-blue-200 text-blue-800',
    icon: 'text-blue-400',
    title: 'text-blue-800',
  },
  success: {
    container: 'bg-green-50 border-green-200 text-green-800',
    icon: 'text-green-400',
    title: 'text-green-800',
  },
  warning: {
    container: 'bg-yellow-50 border-yellow-200 text-yellow-800',
    icon: 'text-yellow-400',
    title: 'text-yellow-800',
  },
  error: {
    container: 'bg-red-50 border-red-200 text-red-800',
    icon: 'text-red-400',
    title: 'text-red-800',
  },
};

const AlertIcon: React.FC<{ variant: keyof typeof alertVariants }> = ({ variant }) => {
  const iconClass = cn('h-5 w-5', alertVariants[variant].icon);

  switch (variant) {
    case 'info':
      return (
        <svg className={iconClass} fill="currentColor" viewBox="0 0 20 20">
          <path
            fillRule="evenodd"
            d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
            clipRule="evenodd"
          />
        </svg>
      );
    case 'success':
      return (
        <svg className={iconClass} fill="currentColor" viewBox="0 0 20 20">
          <path
            fillRule="evenodd"
            d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
            clipRule="evenodd"
          />
        </svg>
      );
    case 'warning':
      return (
        <svg className={iconClass} fill="currentColor" viewBox="0 0 20 20">
          <path
            fillRule="evenodd"
            d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
            clipRule="evenodd"
          />
        </svg>
      );
    case 'error':
      return (
        <svg className={iconClass} fill="currentColor" viewBox="0 0 20 20">
          <path
            fillRule="evenodd"
            d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
            clipRule="evenodd"
          />
        </svg>
      );
    default:
      return null;
  }
};

export const Alert = React.forwardRef<HTMLDivElement, AlertProps>(
  ({ className, variant = 'info', title, children, dismissible = false, onDismiss, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          'rounded-md border p-4',
          alertVariants[variant].container,
          className
        )}
        role="alert"
        {...props}
      >
        <div className="flex">
          <div className="flex-shrink-0">
            <AlertIcon variant={variant} />
          </div>
          <div className="ml-3 flex-1">
            {title && (
              <h3 className={cn('text-sm font-medium', alertVariants[variant].title)}>
                {title}
              </h3>
            )}
            <div className={cn('text-sm', title && 'mt-2')}>
              {children}
            </div>
          </div>
          {dismissible && onDismiss && (
            <div className="ml-auto pl-3">
              <div className="-mx-1.5 -my-1.5">
                <button
                  type="button"
                  className={cn(
                    'inline-flex rounded-md p-1.5 focus:outline-none focus:ring-2 focus:ring-offset-2',
                    'hover:bg-opacity-20 hover:bg-gray-600',
                    alertVariants[variant].icon
                  )}
                  onClick={onDismiss}
                  aria-label="Dismiss alert"
                >
                  <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                    <path
                      fillRule="evenodd"
                      d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                      clipRule="evenodd"
                    />
                  </svg>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
);

Alert.displayName = 'Alert';
