// ui/src/lib/components/organisms/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { onMount } from 'svelte';
  import { 
    DashboardIcon, 
    TasksIcon, 
    ActionsIcon, 
    TriggersIcon, 
    UserIcon, 
    LogoutIcon,
    MenuIcon,
    ChevronLeftIcon,
    ChevronDownIcon,
    XIcon,
    SettingsIcon
  } from '../icons';
  import type { NavigationItem, User } from '$lib/types';
  import ThemeToggle from '../atoms/ThemeToggle.svelte';

  interface Props {
    user?: User;
    onLogout?: () => void;
    collapsed?: boolean;
    onToggle?: (collapsed: boolean) => void;
    items?: NavigationItem[];
    class?: string;
  }

  let { 
    user, 
    onLogout, 
    collapsed = false,
    onToggle,
    items,
    class: className = '' 
  }: Props = $props();

  let mobileMenuOpen = $state(false);
  let userDropdownOpen = $state(false);
  let isMobile = $state(false);

  // Default navigation items if none provided
  const defaultNavigationItems: NavigationItem[] = [
    {
      id: 'dashboard',
      label: 'Dashboard',
      href: '/',
      icon: DashboardIcon
    },
    {
      id: 'tasks',
      label: 'Tasks',
      href: '/tasks',
      icon: TasksIcon
    },
    {
      id: 'actions',
      label: 'Actions',
      href: '/actions',
      icon: ActionsIcon
    },
    {
      id: 'triggers',
      label: 'Triggers',
      href: '/triggers',
      icon: TriggersIcon
    }
  ];

  const navigationItems = items || defaultNavigationItems;

  // Check if we're on mobile
  onMount(() => {
    const checkMobile = () => {
      isMobile = window.innerWidth < 768;
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    
    return () => {
      window.removeEventListener('resize', checkMobile);
    };
  });

  function isActive(href: string): boolean {
    if (href === '/') {
      return $page.url.pathname === '/';
    }
    return $page.url.pathname.startsWith(href);
  }

  function handleToggle() {
    if (isMobile) {
      mobileMenuOpen = !mobileMenuOpen;
    } else {
      const newCollapsed = !collapsed;
      if (onToggle) {
        onToggle(newCollapsed);
      }
    }
  }

  function closeMobileMenu() {
    mobileMenuOpen = false;
  }

  function toggleUserDropdown() {
    userDropdownOpen = !userDropdownOpen;
  }

  // Close dropdowns when clicking outside
  function handleClickOutside(event: MouseEvent) {
    const target = event.target as Element;
    if (!target.closest('[data-dropdown="user"]')) {
      userDropdownOpen = false;
    }
  }

  onMount(() => {
    document.addEventListener('click', handleClickOutside);
    return () => {
      document.removeEventListener('click', handleClickOutside);
    };
  });
</script>

<!-- Mobile Menu Button -->
{#if isMobile}
  <button
    onclick={handleToggle}
    class="fixed top-4 left-4 z-50 p-2 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 md:hidden"
    aria-label="Toggle navigation menu"
  >
    {#if mobileMenuOpen}
      <XIcon class="w-5 h-5 text-gray-600 dark:text-gray-300" />
    {:else}
      <MenuIcon class="w-5 h-5 text-gray-600 dark:text-gray-300" />
    {/if}
  </button>
{/if}

<!-- Mobile Overlay -->
{#if isMobile && mobileMenuOpen}
  <div 
    class="fixed inset-0 bg-black bg-opacity-50 z-40 md:hidden"
    onclick={closeMobileMenu}
    onkeydown={(e) => e.key === 'Escape' && closeMobileMenu()}
    role="button"
    tabindex="0"
    aria-label="Close navigation menu"
  ></div>
{/if}

<!-- Sidebar -->
<aside 
  class="fixed top-0 left-0 z-40 h-screen bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 transition-all duration-300 ease-in-out {className}
    {isMobile 
      ? mobileMenuOpen 
        ? 'translate-x-0 w-64' 
        : '-translate-x-full w-64'
      : collapsed 
        ? 'w-16' 
        : 'w-64'
    }"
  role="navigation"
  aria-label="Main navigation"
>
  <!-- Brand -->
  <div class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
    <a href="/" class="flex items-center space-x-3 min-w-0">
      <img 
        src="https://cdn-icons-png.freepik.com/128/12707/12707916.png" 
        alt="Strøm" 
        class="w-8 h-8 flex-shrink-0"
      />
      {#if !collapsed || isMobile}
        <span class="text-xl font-semibold text-gray-900 dark:text-white truncate">
          Strøm
        </span>
      {/if}
    </a>
    
    <!-- Desktop Collapse Button -->
    {#if !isMobile}
      <button
        onclick={handleToggle}
        class="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
        aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
      >
        <ChevronLeftIcon 
          class="w-4 h-4 text-gray-500 dark:text-gray-400 transition-transform duration-200 {collapsed ? 'rotate-180' : ''}" 
        />
      </button>
    {/if}
  </div>

  <!-- Navigation -->
  <nav class="flex-1 overflow-y-auto p-4">
    <ul class="space-y-2">
      {#each navigationItems as item}
        <li>
          {#if item.children && item.children.length > 0}
            <!-- Navigation item with children (future enhancement) -->
            <div class="space-y-1">
              <button
                class="w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800 transition-colors duration-200"
              >
                <div class="flex items-center space-x-3">
                  {#if item.icon}
                    {@const IconComponent = item.icon}
                    <IconComponent class="w-5 h-5 flex-shrink-0" />
                  {/if}
                  {#if !collapsed || isMobile}
                    <span class="truncate">{item.label}</span>
                  {/if}
                </div>
                {#if !collapsed || isMobile}
                  <ChevronDownIcon class="w-4 h-4" />
                {/if}
              </button>
            </div>
          {:else}
            <!-- Regular navigation item -->
            <a
              href={item.href}
              onclick={isMobile ? closeMobileMenu : undefined}
              class="flex items-center px-3 py-2 rounded-lg text-sm font-medium transition-colors duration-200 group relative
                {isActive(item.href || '') 
                  ? 'bg-blue-50 text-blue-700 dark:bg-blue-900/20 dark:text-blue-400' 
                  : 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800'}"
              aria-current={isActive(item.href || '') ? 'page' : undefined}
            >
              {#if item.icon}
                {@const IconComponent = item.icon}
                <IconComponent class="w-5 h-5 flex-shrink-0" />
              {/if}
              
              {#if !collapsed || isMobile}
                <span class="ml-3 truncate">{item.label}</span>
                {#if item.badge}
                  <span class="ml-auto bg-blue-100 text-blue-800 text-xs font-medium px-2 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300">
                    {item.badge}
                  </span>
                {/if}
              {:else if item.badge}
                <!-- Collapsed badge indicator -->
                <span class="absolute -top-1 -right-1 w-2 h-2 bg-blue-500 rounded-full"></span>
              {/if}
              
              <!-- Tooltip for collapsed state -->
              {#if collapsed && !isMobile}
                <div class="absolute left-full ml-2 px-2 py-1 bg-gray-900 text-white text-xs rounded opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 whitespace-nowrap z-50">
                  {item.label}
                  {#if item.badge}
                    <span class="ml-1 bg-blue-600 px-1 rounded">
                      {item.badge}
                    </span>
                  {/if}
                </div>
              {/if}
            </a>
          {/if}
        </li>
      {/each}
    </ul>
  </nav>

  <!-- User Profile -->
  {#if user}
    <div class="border-t border-gray-200 dark:border-gray-700 p-4">
      <div class="relative" data-dropdown="user">
        <button
          onclick={toggleUserDropdown}
          class="w-full flex items-center space-x-3 px-3 py-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors duration-200 group"
          aria-expanded={userDropdownOpen}
          aria-haspopup="true"
        >
          <div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center flex-shrink-0">
            <UserIcon class="w-4 h-4 text-white" />
          </div>
          
          {#if !collapsed || isMobile}
            <div class="flex-1 min-w-0 text-left">
              <p class="text-sm font-medium text-gray-900 dark:text-white truncate">
                {user.name || 'User'}
              </p>
              <p class="text-xs text-gray-500 dark:text-gray-400 truncate">
                {user.email}
              </p>
            </div>
            <ChevronDownIcon 
              class="w-4 h-4 text-gray-400 transition-transform duration-200 {userDropdownOpen ? 'rotate-180' : ''}" 
            />
          {:else}
            <!-- Tooltip for collapsed state -->
            <div class="absolute left-full ml-2 px-2 py-1 bg-gray-900 text-white text-xs rounded opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 whitespace-nowrap z-50">
              {user.name || 'User'}
              <br />
              {user.email}
            </div>
          {/if}
        </button>

        <!-- User Dropdown Menu -->
        {#if userDropdownOpen && (!collapsed || isMobile)}
          <div class="absolute bottom-full left-0 right-0 mb-2 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 py-1">
            <a
              href="/profile"
              class="flex items-center px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
              onclick={isMobile ? closeMobileMenu : undefined}
            >
              <UserIcon class="w-4 h-4 mr-3" />
              Profile
            </a>
            <a
              href="/settings"
              class="flex items-center px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
              onclick={isMobile ? closeMobileMenu : undefined}
            >
              <SettingsIcon class="w-4 h-4 mr-3" />
              Settings
            </a>
            <div class="flex items-center justify-between px-4 py-2">
              <span class="text-sm text-gray-700 dark:text-gray-300">Theme</span>
              <ThemeToggle size="sm" />
            </div>
            <hr class="my-1 border-gray-200 dark:border-gray-600" />
            {#if onLogout}
              <button
                onclick={() => {
                  onLogout?.();
                  if (isMobile) closeMobileMenu();
                }}
                class="w-full flex items-center px-4 py-2 text-sm text-red-600 dark:text-red-400 hover:bg-gray-100 dark:hover:bg-gray-700"
              >
                <LogoutIcon class="w-4 h-4 mr-3" />
                Logout
              </button>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  {/if}
</aside>

// ui/src/components/layout/Sidebar.tsx
import React, { useState, useRef, useEffect } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';

interface SidebarProps {
  isOpen: boolean;
  onClose: () => void;
  isCollapsed?: boolean;
  onToggleCollapse?: () => void;
}

interface NavigationItem {
  name: string;
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  current?: boolean;
}

// Icon components
const DashboardIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true">
    <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
  </svg>
);

const TasksIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true">
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3-6h3.75m-3.75 3h3.75m-3.75 3h3.75M5.25 6.75h13.5a2.25 2.25 0 012.25 2.25v10.5a2.25 2.25 0 01-2.25 2.25H5.25a2.25 2.25 0 01-2.25-2.25V9a2.25 2.25 0 012.25-2.25z" />
  </svg>
);

const JobsIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true">
    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 3m8.5-3l1 3m0 0l.5 1.5m-.5-1.5h-9.5m0 0l-.5 1.5m.75-9l3-3 2.148 2.148A12.061 12.061 0 0116.5 7.605" />
  </svg>
);

export const Sidebar: React.FC<SidebarProps> = ({ isOpen, onClose, isCollapsed = false, onToggleCollapse }) => {
  const { user, logout } = useAuth();
  const location = useLocation();
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const userMenuRef = useRef<HTMLLIElement>(null);

  // Close user menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (userMenuRef.current && !userMenuRef.current.contains(event.target as Node)) {
        setUserMenuOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const navigation: NavigationItem[] = [
    { name: 'Dashboard', href: '/dashboard', icon: DashboardIcon },
    { name: 'Tasks', href: '/tasks', icon: TasksIcon },
    { name: 'Jobs', href: '/jobs', icon: JobsIcon },
  ];

  const handleLogout = () => {
    logout();
    setUserMenuOpen(false);
    onClose();
  };

  // Handle keyboard navigation
  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Escape') {
      onClose();
    }
  };

  return (
    <>
      {/* Desktop sidebar */}
      <div className={`hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:flex-col transition-all duration-300 ${isCollapsed ? 'lg:w-16' : 'lg:w-64'}`}>
        <div className="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-900 px-6 pb-4">
          {/* Logo and collapse button */}
          <div className="flex h-16 shrink-0 items-center justify-between">
            <h1 className={`text-white text-xl font-bold transition-opacity duration-300 ${isCollapsed ? 'opacity-0' : 'opacity-100'}`}>
              {!isCollapsed && 'Strøm'}
            </h1>
            <button
              onClick={onToggleCollapse}
              className="text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 rounded p-1"
              aria-label={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
            >
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
                {isCollapsed ? (
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                ) : (
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                )}
              </svg>
            </button>
          </div>

          {/* Navigation */}
          <nav className="flex flex-1 flex-col" aria-label="Main navigation">
            <ul role="list" className="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" className="-mx-2 space-y-1">
                  {navigation.map((item) => {
                    const isActive = location.pathname === item.href;
                    return (
                      <li key={item.name}>
                        <NavLink
                          to={item.href}
                          className={({ isActive }) =>
                            `group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold transition-colors ${
                              isActive
                                ? 'bg-gray-800 text-white'
                                : 'text-gray-400 hover:text-white hover:bg-gray-800'
                            }`
                          }
                          aria-current={isActive ? 'page' : undefined}
                          title={isCollapsed ? item.name : undefined}
                        >
                          <item.icon
                            className="h-6 w-6 shrink-0"
                            aria-hidden="true"
                          />
                          {!isCollapsed && item.name}
                        </NavLink>
                      </li>
                    );
                  })}
                </ul>
              </li>

              {/* User profile section */}
              <li className="mt-auto" ref={userMenuRef}>
                <div className="relative">
                  <button
                    onClick={() => setUserMenuOpen(!userMenuOpen)}
                    className={`flex items-center gap-x-4 px-2 py-3 text-sm font-semibold leading-6 text-white border-t border-gray-700 hover:bg-gray-800 rounded-md transition-colors w-full ${
                      isCollapsed ? 'justify-center' : ''
                    }`}
                    aria-expanded={userMenuOpen}
                    aria-haspopup="true"
                  >
                    <div className="h-8 w-8 rounded-full bg-blue-500 flex items-center justify-center flex-shrink-0">
                      <span className="text-sm font-medium text-white">
                        {user?.name ? user.name.charAt(0).toUpperCase() : user?.email.charAt(0).toUpperCase()}
                      </span>
                    </div>
                    {!isCollapsed && (
                      <>
                        <div className="flex-1 min-w-0 text-left">
                          <div className="text-sm font-medium text-white truncate">
                            {user?.name || 'User'}
                          </div>
                          <div className="text-xs text-gray-400 truncate">
                            {user?.email}
                          </div>
                        </div>
                        <svg className="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />
                        </svg>
                      </>
                    )}
                  </button>

                  {/* User dropdown menu */}
                  {userMenuOpen && (
                    <div
                      className={`absolute bottom-full mb-2 ${isCollapsed ? 'left-0' : 'right-0'} z-10 w-48 origin-bottom-${isCollapsed ? 'left' : 'right'} rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none`}
                      role="menu"
                      aria-orientation="vertical"
                      aria-labelledby="user-menu-button"
                    >
                      <div className="px-4 py-2 text-sm text-gray-700 border-b border-gray-100">
                        <div className="font-medium">{user?.name || 'User'}</div>
                        <div className="text-gray-500 text-xs">{user?.email}</div>
                      </div>

                      <button
                        className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none"
                        role="menuitem"
                        onClick={handleLogout}
                      >
                        Sign out
                      </button>
                    </div>
                  )}
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>

      {/* Mobile sidebar */}
      <div
        className={`lg:hidden fixed inset-y-0 z-50 flex w-64 flex-col transform transition-transform duration-300 ease-in-out ${
          isOpen ? 'translate-x-0' : '-translate-x-full'
        }`}
        onKeyDown={handleKeyDown}
      >
        <div className="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-900 px-6 pb-4">
          {/* Mobile header with close button */}
          <div className="flex h-16 shrink-0 items-center justify-between">
            <h1 className="text-white text-xl font-bold">Strøm</h1>
            <button
              type="button"
              className="text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 rounded p-1"
              onClick={onClose}
              aria-label="Close sidebar"
            >
              <span className="sr-only">Close sidebar</span>
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Mobile navigation */}
          <nav className="flex flex-1 flex-col" aria-label="Main navigation">
            <ul role="list" className="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" className="-mx-2 space-y-1">
                  {navigation.map((item) => {
                    const isActive = location.pathname === item.href;
                    return (
                      <li key={item.name}>
                        <NavLink
                          to={item.href}
                          onClick={onClose}
                          className={({ isActive }) =>
                            `group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold transition-colors ${
                              isActive
                                ? 'bg-gray-800 text-white'
                                : 'text-gray-400 hover:text-white hover:bg-gray-800'
                            }`
                          }
                          aria-current={isActive ? 'page' : undefined}
                        >
                          <item.icon
                            className="h-6 w-6 shrink-0"
                            aria-hidden="true"
                          />
                          {item.name}
                        </NavLink>
                      </li>
                    );
                  })}
                </ul>
              </li>

              {/* Mobile user profile section */}
              <li className="mt-auto">
                <div className="flex items-center gap-x-4 px-2 py-3 text-sm font-semibold leading-6 text-white border-t border-gray-700">
                  <div className="h-8 w-8 rounded-full bg-blue-500 flex items-center justify-center">
                    <span className="text-sm font-medium text-white">
                      {user?.name ? user.name.charAt(0).toUpperCase() : user?.email.charAt(0).toUpperCase()}
                    </span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-white truncate">
                      {user?.name || 'User'}
                    </div>
                    <div className="text-xs text-gray-400 truncate">
                      {user?.email}
                    </div>
                  </div>
                  <button
                    onClick={handleLogout}
                    className="text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 rounded p-1"
                    aria-label="Sign out"
                    title="Sign out"
                  >
                    <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" aria-hidden="true">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                    </svg>
                  </button>
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </>
  );
};
